title: Bold Outlook
description: Keeping designers and developers informed
show_downloads: false
google_analytics: UA-76958710-17
remote_theme: brandonhimpfen/journal
permalink: pretty
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:slug/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
paginate: 6
paginate_path: "/page:num/"
